version: 2.1

orbs:
  node: circleci/node@4.1.0

nightly:
  triggers:
    - cron: "2 * * * *   "
    - cron: "0 20 * * *"

jobs:
  build:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run:
          name: Grant Permission
          command: chmod +x mvnw
      - run:
          name: Run Test
          command: mvn -Dmaven.test.skip=true package

  test-case-1:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run:
          name: Grant Permission
          command: chmod +x mvnw
      - run:
          name: Run Test
          command: mvn test


workflows:
  version: 2.1
  auto-flow:
    jobs:
      - build