version: 2.1

orbs:
  node: circleci/node@4.1.0

nightly:
  triggers:
    - cron: "2 * * * *   "
    - cron: "0 20 * * *"

jobs:
  package:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run:
          name: Grant Permission
          command: chmod +x mvnw
      - run:
          name: Run Test
          command: mvn -Dmaven.test.skip=true package

  test-case-1:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run:
          name: Grant Permission
          command: chmod +x mvnw
      - run:
          name: Run Test
          command: mvn test

  test-case-2:
    docker:
      - image: cimg/node:12.6
    steps:
      - checkout
      - node/install-packages:
         override-ci-command: npm install
      - run:
          name: Install jest
          command: npm install --save-dev jest
      - run:
          name: Node Test ((skipping))
          command: echo "npm run test"

  test-case-3:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run:
          name: Grant Permission
          command: chmod +x mvnw
      - run:
          name: Java Test ((skipping))
          command: mvn test
  
  test-case-4:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run:
          name: Grant Permission
          command: chmod +x mvnw
      - run:
          name: Java Test ((skipping))
          command: mvn test


workflows:
  version: 2.1
  auto-flow:
    jobs:
      - package
      - test-case-1:
          requires:
            - package
      - test-case-2:
          requires:
            - package
      - test-case-3:
          requires:
            - package
      - test-case-4:
          requires:
            - package