version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:
  build:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run:
          name: Grant Permission
          command: chmod +x mvnw
      - run:
          name: Run Test
          command: ./mvnw -Dmaven.test.skip=true package
